name: Python Flask CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Replace with the version of Python you want to use

    - name: Install pip
      run: |
        python -m ensurepip --default-pip
        python -m pip install --upgrade pip setuptools wheel

    - name: Install Flask
      run: |
        pip install Flask
